name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: ^0.7.4    # launcher icon
  
  http: ^0.12.0+2                   # http package
  charts_flutter: ^0.8.1            # generating charts
  rflutter_alert: ^1.0.2            # alert dialogs
  flushbar:
    git:
      url: git://github.com/valterh4ck3r/flushbar
      ref: master                 # for showing alerts at bottom or top

  html: ^0.13.3+3                   # webscraping
  # flutter_webview_plugin: ^0.3.10   # webview with flutter
  dio: ^3.0.7                       # http wrapper
#  sqflite: ^1.2.0                   # sqlite with flutter
  shared_preferences: ^0.5.6
#  path_provider: ^0.4.1
  flutter_slidable: ^0.5.4          # slide left to delete
  bubble_bottom_bar: ^1.2.0         # bottom navigation bar

  qr_flutter: ^3.2.0                # QR code generator only
  barcode_scan: ^1.0.0              # QR and barcode reader from camera
  qr_code_tools: ^0.0.6             # QR reader from file
  image_picker: 0.6.2+3             # pick image from gallery

  form_bloc: ^0.5.1                 # creating forms
  flutter_form_bloc: ^0.4.2         # part of form BLoC
  flutter_bloc: ^0.21.0             # flutter BLoC

  flutter_speed_dial: ^1.2.5        # multiple Floating Action Buttons
  url_launcher: ^5.4.1              # Launch from native web browser

  animator: 1.0.0+5                 # Animator library
  flutter_circular_chart: ^0.1.0    # circular charts

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icons/clem_logo_cropped.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/darker-rain.jpg
    - assets/images/clem_logo_placeholder.jpg
    - assets/icons/clem_logo_cropped.png
    - assets/images/
    - assets/icons/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
